[en]
  languageName = "English"
  weight = 1

[zh-cn]
  languageName = "简体中文"
  weight = 4
  [zh-cn.params]
    dateFormat = "2006-01-02"
    description = "一个快速、响应式和功能丰富的 Hugo 博客主题"
    keywords = "Hugo, Bootstrap, 博客主题"
    [zh-cn.params.archive]
      dateFormat = "01-02"
